language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  verbose: true
  on:
    branch: master